#!/usr/bin/env bash                                                                                                                                      
#SBATCH --job-name=tester                                                                                                                               
#SBATCH --partition=batch                                                                                                                                
#SBATCH --account=free                                                                                                                                   
#SBATCH --nodes=1

#SBATCH --array=26-249
                                                                                                                                       
#SBATCH --ntasks-per-node=16                                                                                                                            
#SBATCH --time=2:00:00                                                                                                                                 
#SBATCH --export=ALL                                                                                                                                    
module load python/3.6
python run_tests_fixed_costs.py ${SLURM_ARRAY_TASK_ID}

